// Curated list of Tabler icon names for the icon picker
export const AVAILABLE_ICONS = [
  "IconLink",
  "IconWorld",
  "IconMail",
  "IconPhone",
  "IconMapPin",
  "IconHeart",
  "IconStar",
  "IconBookmark",
  "IconShoppingCart",
  "IconMusic",
  "IconCamera",
  "IconVideo",
  "IconMicrophone",
  "IconHeadphones",
  "IconPalette",
  "IconBrush",
  "IconPencil",
  "IconCode",
  "IconTerminal",
  "IconDatabase",
  "IconCloud",
  "IconRocket",
  "IconBolt",
  "IconFlame",
  "IconDiamond",
  "IconCrown",
  "IconTrophy",
  "IconTarget",
  "IconChartBar",
  "IconPresentation",
  "IconBriefcase",
  "IconBuilding",
  "IconHome",
  "IconCar",
  "IconPlane",
  "IconSchool",
  "IconBook",
  "IconNews",
  "IconCalendar",
  "IconClock",
  "IconGift",
  "IconCoffee",
  "IconPizza",
  "IconDeviceGamepad",
  "IconBallFootball",
  "IconRun",
  "IconYoga",
  "IconStethoscope",
  "IconPill",
  "IconBrandInstagram",
  "IconBrandGoogle",
] as const;

export type IconName = (typeof AVAILABLE_ICONS)[number];
